#!/bin/bash
# build-arm64-debug.sh — DEBUG variant of the arm64 desktop image with SSH.
#
# Overlays TinySSH (the `sshd` superserver + `tinysshd`) + a baked authorized
# ed25519 pubkey onto the normal 1:1 desktop staging tree, so we can
# `ssh live@<pi>` in for on-device debugging (dhcp already brings up networking
# at boot). This is a DEBUG image ONLY — it bakes a fixed authorized key and is
# never a release artifact; the normal build (build-arm64-desktop.sh) has no
# sshd. Separate script = separate, opt-in build path.
#
# Usage:  SSH_PUBKEY="ssh-ed25519 AAAA... comment" bash tools/build-arm64-debug.sh
set -euo pipefail
REPO="${REPO:-/root/loricaos}"
W="$REPO/build/musl-arm64/bin/aarch64-musl-gcc"
STRIP=aarch64-linux-gnu-strip
STAGE="$REPO/build/arm64-server/rootfs"
OUT_EXT2="$REPO/build/arm64-desktop/rootfs.ext2"
PUBKEY="${SSH_PUBKEY:?set SSH_PUBKEY to the authorized ed25519 pubkey line}"
log(){ echo "[arm64-debug] $*"; }

# 1. Normal 1:1 desktop first (builds the staging tree + packs rootfs.ext2).
log "== build desktop base =="
bash "$REPO/tools/build-arm64-desktop.sh"

# 2. Cross-build TinySSH for arm64. TinySSH's feature detection is compile/link-
#    based; the has*.h generated by the native build (build-tinyssh.sh) encode
#    the same static-musl/Aegis results, so a clean cross build reuses them.
TS="$REPO/references/tinyssh-arm64"
if [ ! -x "$TS/tinysshd" ]; then
    log "== cross-build tinysshd =="
    [ -d "$REPO/references/tinyssh" ] || { echo "need references/tinyssh (run build-tinyssh.sh once)"; exit 1; }
    rm -rf "$TS"; cp -r "$REPO/references/tinyssh" "$TS"
    ( cd "$TS" && rm -f ./*.o tinysshd tinysshd-makekey tinysshd-printkey && \
      make CC="$W" CPPFLAGS="-Icryptoint -I." CFLAGS="-Os -D_GNU_SOURCE" LDFLAGS="-static" \
           tinysshd tinysshd-makekey tinysshd-printkey )
fi

# 3. Cross-build the sshd superserver (listen :22 → fork → exec tinysshd).
log "== build sshd superserver =="
"$W" -Os -static -Wall -o "$REPO/build/sshd-arm64" "$REPO/user/bin/sshd/main.c"

# 4. Install binaries into the staging tree.
inst(){ cp "$1" "$STAGE/bin/$2"; "$STRIP" -s "$STAGE/bin/$2" 2>/dev/null || true; chmod 0755 "$STAGE/bin/$2"; }
inst "$REPO/build/sshd-arm64" sshd
inst "$TS/tinysshd"           tinysshd
cp "$TS/tinysshd" "$STAGE/bin/tinysshd-makekey"; chmod 0755 "$STAGE/bin/tinysshd-makekey"
cp "$TS/tinysshd" "$STAGE/bin/tinysshd-printkey"; chmod 0755 "$STAGE/bin/tinysshd-printkey"

# 5. Pre-generate host keys (ed25519 key bytes are arch-independent, so the x86
#    tinysshd-makekey output is a valid host key on the Pi). sshd also generates
#    on first boot if missing; pre-generating keeps the host key stable.
rm -rf "$STAGE/etc/tinyssh/sshkeydir"
"$REPO/build/tinyssh/tinysshd-makekey" "$STAGE/etc/tinyssh/sshkeydir"

# 6. authorized_keys for the uid-0 login user (arm64 passwd's uid 0 is 'live').
install -d -m 700 "$STAGE/home/live/.ssh"
printf '%s\n' "$PUBKEY" > "$STAGE/home/live/.ssh/authorized_keys"
chmod 600 "$STAGE/home/live/.ssh/authorized_keys"

# 7. caps + vigil service.
echo "service NET_SOCKET NET_LISTEN" > "$STAGE/etc/aegis/caps.d/sshd"
cp "$REPO/rootfs/etc/aegis/caps.d/tinysshd" "$STAGE/etc/aegis/caps.d/" 2>/dev/null || true
mkdir -p "$STAGE/etc/vigil/services/sshd"
cp "$REPO/rootfs/etc/vigil/services/sshd/"* "$STAGE/etc/vigil/services/sshd/"
echo live > "$STAGE/etc/vigil/services/sshd/user"   # uid-0 user on arm64 is 'live'

# 8. Repack the ext2 with the SSH overlay.
log "== repack ext2 (with sshd) =="
rm -f "$OUT_EXT2"
/sbin/mke2fs -q -t ext2 -b 4096 -d "$STAGE" -L aegis-arm64 "$OUT_EXT2" 128M
log "done: $OUT_EXT2 ($(stat -c%s "$OUT_EXT2") bytes) — ssh live@<pi-ip>"
