#!/bin/sh
# gen-limine-conf.sh — single source of truth for every Aegis boot config.
#
# Emits a Limine v11.x `limine.conf` to stdout for the requested build mode.
# This one script replaces the four drifting GRUB configs (grub.cfg,
# grub-test.cfg, grub-installer-test.cfg, grub-installed.cfg). The modes differ
# only in: timeout, which kernel partition the loader reads (the boot media for
# live ISOs vs the installed ext2 root by GPT GUID), whether the rootfs/esp
# ramdisks are passed as multiboot2 modules, and the kernel cmdline.
#
# Usage: gen-limine-conf.sh <mode>
#   live            aegis.iso              graphical default; graphical/text/debug; modules
#   test            aegis-test.iso         single text entry; timeout 0; modules
#   installer-test  aegis-installer-test.iso  single graphical autologin entry; timeout 0; modules
#   installed       esp.img (on-disk ESP)  graphical/text/debug; kernel from ext2 by GUID; NO modules
#
# The kernel is multiboot2 and unchanged; Limine passes modules in config order
# (first = rootfs/ramdisk0, second = esp/ramdisk1) and a 32bpp linear
# framebuffer via the multiboot2 framebuffer tag — so there is no gfxmode to set.
set -eu

mode="${1:?usage: gen-limine-conf.sh <live|test|installer-test|installed>}"

# Every mode loads the kernel from the partition Limine itself booted from
# (`boot()`): the ISO9660 volume for the live ISOs, or the FAT ESP for the
# installed system. The installed system's ESP carries its own copy of
# aegis.elf (Makefile bakes it into esp.img) — Limine reads FAT reliably,
# whereas its ext2 driver chokes on our rootfs (1 KiB blocks / dir_index).
# The kernel then mounts the real ext2 root from nvme itself, so the installed
# entries need no ramdisk modules.
KPATH="boot():/boot/aegis.elf"

# Live media (anything booted from the ISO) marks the cmdline with
# aegis_live=1. Userspace branches on it: vigil removes the installer
# binaries on unmarked (installed) boots; citadel-dock only shows the
# installer icon on marked (live) boots.
case "$mode" in
    installed)
        WITH_MODULES=0
        TIMEOUT=3
        LIVE_ARG=""
        ;;
    live)
        WITH_MODULES=1
        TIMEOUT=3
        LIVE_ARG=" aegis_live=1"
        ;;
    server)
        # Server live ISO: text console only (no compositor to boot into).
        WITH_MODULES=1
        TIMEOUT=3
        LIVE_ARG=" aegis_live=1"
        ;;
    server-installed)
        # Installed server: text console only, boots ext2 root from disk.
        WITH_MODULES=0
        TIMEOUT=3
        LIVE_ARG=""
        ;;
    test|installer-test|dltest|perfbench|selftest|infer)
        WITH_MODULES=1
        TIMEOUT=0
        LIVE_ARG=" aegis_live=1"
        ;;
    *)
        echo "gen-limine-conf.sh: unknown mode '$mode'" >&2
        exit 1
        ;;
esac

emit_entry() {  # $1 = title, $2 = cmdline
    printf '/%s\n' "$1"
    printf '    protocol: multiboot2\n'
    printf '    path: %s\n' "$KPATH"
    if [ "$WITH_MODULES" = 1 ]; then
        printf '    module_path: boot():/boot/rootfs.img\n'
        printf '    module_path: boot():/boot/esp.img\n'
    fi
    printf '    cmdline: %s\n\n' "$2"
}

printf '# Generated by tools/gen-limine-conf.sh (mode: %s) — do not edit by hand.\n' "$mode"
printf 'timeout: %s\n\n' "$TIMEOUT"

case "$mode" in
    live|installed)
        emit_entry "Aegis (graphical)" "boot=graphical quiet$LIVE_ARG"
        emit_entry "Aegis (text)"      "boot=text quiet$LIVE_ARG"
        emit_entry "Aegis (debug)"     "boot=text$LIVE_ARG"
        # Graphical boot with the greeter input-diagnostics line enabled
        # (greeter_diag). Off by default so production greeters are clean;
        # selectable here for serial-less "is the keyboard alive?" triage.
        emit_entry "Aegis (input diagnostics)" "boot=graphical greeter_diag$LIVE_ARG"
        ;;
    test)
        emit_entry "Aegis (test)" "boot=text quiet$LIVE_ARG"
        ;;
    installer-test)
        emit_entry "Aegis (installer-test)" "boot=graphical quiet bastion_autologin=root$LIVE_ARG"
        ;;
    dltest)
        emit_entry "Aegis (dltest)" "boot=text quiet dltest$LIVE_ARG"
        ;;
    perfbench)
        emit_entry "Aegis (perfbench)" "boot=text quiet perfbench_ipc perfbench_fs$LIVE_ARG"
        ;;
    selftest)
        emit_entry "AspisOS (selftest)" "boot=text quiet selftest$LIVE_ARG"
        ;;
    infer)
        # No explicit boot= — exercises vigil's mode inference (graphical iff
        # the compositor is installed). Used by the desktop-package test to
        # prove a box with the graphical stack present comes up to the greeter
        # exactly as it would on the reboot after `herald install desktop`.
        emit_entry "AspisOS (infer)" "quiet$LIVE_ARG"
        ;;
    server)
        # Live server ISO: explicit text console — this is the installer
        # environment and has no compositor to boot into.
        emit_entry "AspisOS Server" "boot=text quiet$LIVE_ARG"
        ;;
    server-installed)
        # Installed server: deliberately NO explicit boot= mode. vigil then
        # infers the mode from whether the graphical stack is present — a bare
        # server has no compositor and comes up to a text login, but after
        # `herald install desktop` lands /bin/bastion the next boot brings up
        # the greeter, with no bootloader edit. (LIVE_ARG is empty here.)
        emit_entry "AspisOS Server" "quiet$LIVE_ARG"
        ;;
esac
