#!/bin/bash
#
# herald-keygen.sh — generate the herald package-signing keypair.
#
#   Produces:
#     $KEYDIR/herald-dev.key      ECDSA P-256 private key (PEM) — used by
#                                 tools/herald-pack.sh to sign packages.
#     $HDR (trusted_key.h)        the matching 65-byte uncompressed public
#                                 point, embedded in the herald binary as the
#                                 trust anchor.
#
# This is a DEVELOPMENT key. A production deployment must generate a real key
# on an offline machine and ship the resulting trusted_key.h. The keypair is
# generated once and reused (idempotent); delete herald-dev.key to rotate.
#
# Usage: herald-keygen.sh [KEYDIR] [HEADER_PATH]
set -e

KEYDIR="${1:-build/herald-keys}"
# Header lives next to the key (both under build/) so `make clean` removes them
# together and they regenerate consistently — never drift.
HDR="${2:-build/herald-keys/trusted_key.h}"
PRIV="$KEYDIR/herald-dev.key"

# Production trust anchor. tools/herald-keys/trusted_key.h is COMMITTED (public
# point only) so every build env — Mac, container, CI, a fresh clone — embeds
# the SAME permanent anchor; `make clean`/`git clean` can no longer mint a new
# one and orphan the deployed repo. The matching private key
# (tools/herald-keys/herald.key) is gitignored and lives on the repo host.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROD_HDR="$SCRIPT_DIR/herald-keys/trusted_key.h"
PROD_KEY="$SCRIPT_DIR/herald-keys/herald.key"

mkdir -p "$KEYDIR"

if [ -f "$PROD_HDR" ]; then
    # Production path: pin the committed anchor. Build needs only the public
    # header; the private key is needed only to SIGN packages (sample/tests),
    # so its absence here is fine — herald.elf still builds.
    cp "$PROD_HDR" "$HDR"
    if [ -f "$PROD_KEY" ]; then
        cp "$PROD_KEY" "$PRIV"
        chmod 600 "$PRIV"
        echo "[herald-keygen] using committed PRODUCTION anchor + signing key"
    else
        # No production private key on this build host. Drop any stale dev key
        # so the sample/test fixture is NOT signed with a key that won't match
        # the committed anchor (the keyless build skips signing cleanly instead).
        rm -f "$PRIV"
        echo "[herald-keygen] using committed PRODUCTION anchor (no private key here; package signing unavailable)"
    fi
    exit 0
fi

# Dev fallback: no committed anchor (e.g. anchor was removed). Generate an
# ephemeral keypair so the tree still builds + signs locally.
if [ ! -f "$PRIV" ]; then
    openssl ecparam -name prime256v1 -genkey -noout -out "$PRIV"
    echo "[herald-keygen] generated dev signing key: $PRIV"
fi

# The SubjectPublicKeyInfo DER for a P-256 key ends with the uncompressed
# public point: 0x04 || X(32) || Y(32) = 65 bytes. Take the last 65 bytes.
POINT_HEX=$(openssl ec -in "$PRIV" -pubout -outform DER 2>/dev/null \
            | tail -c 65 | od -An -v -tx1 | tr -d ' \n')

if [ "${#POINT_HEX}" -ne 130 ]; then
    echo "[herald-keygen] ERROR: extracted public point is ${#POINT_HEX} hex chars, expected 130" >&2
    exit 1
fi
if [ "${POINT_HEX:0:2}" != "04" ]; then
    echo "[herald-keygen] ERROR: public point does not start with 0x04 (got 0x${POINT_HEX:0:2})" >&2
    exit 1
fi

{
    echo "/* GENERATED by tools/herald-keygen.sh — DEV signing key. Do not edit. */"
    echo "#ifndef HERALD_TRUSTED_KEY_H"
    echo "#define HERALD_TRUSTED_KEY_H"
    echo "static const unsigned char herald_trusted_key[65] = {"
    echo "$POINT_HEX" | sed 's/\(..\)/0x\1,/g' | fold -w 60 | sed 's/^/    /'
    echo "};"
    echo "#endif"
} > "$HDR"

echo "[herald-keygen] wrote trust anchor: $HDR"
